---
common:
  image: busybox
  volumes:
    - /usr/local/share/ca-certificates/

gitlab:
  hostname: gitlab
  container_name: gitlab
  build: ./gitlab
  expose:
    - "80"
    - "443"
  ports:
    - "80:80"
    - "443:443"
  environment:
    VIRTUAL_HOST: gitlab
    GITLAB_OMNIBUS_CONFIG: "external_url 'https://gitlab:443/'"
  volumes_from:
    - common
  # default credentials:  root:5iveL!fe

oauthapp:
  hostname: oauthapp
  container_name: oauth_gitlab_app
  build: ./oauth_app
  expose:
    - "80"
    - "8080"
  links:
    - "gitlab"
  ports:
    - "8080:443"
  environment:
    OAUTHLIB_INSECURE_TRANSPORT: 1          # ONLY FOR DEVELOPMENT
    UWSGI_EXTRA_PARAMS: "--py-autoreload 1" # ONLY FOR DEVELOPMENT
  restart: always
  # OS X + VirtualBox + Docker nightmares...
  volumes:
    - /Users:/Users
  volumes_from:
    - common
  working_dir: "/Users/gyorgydemarcsek/oauth2_gitlab_demo/oauth-gitlab-app/app"
